name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Phase de compilation
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd $HOME
