name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          git clone https://github.com/${{ github.repository }}.git
          ls
          tree
